services:
  - type: web
    name: addiction-backend
    env: node
    buildCommand: "npm install"
    startCommand: "node server.js"
    plan: free
    runtime: node 16
    envVars:
      - key: GITHUB_TOKEN
        fromSecret: github-token
